### ISSUE TITLE
Checking the credibility of the token

### ISSUE THREAD

**Issue by rakeen** [auth0/auth0-angular2#20]
In the example we're just showing the components by checking the expiry date in the json token that was stored in the client side.  
It could be the case that the client tampers the token and increases the expiration time. We're not checking that here are we(we would be needing the key which was used to sign that token) ?

**Comment by chenkie** [comment]
You bet--the only real indication of whether or not the user is authenticated on the client side is the expiry, which can be tampered with. However, that tampering cannot affect access to resources on the server side because the JWT is digitally signed. If it were tampered with it would be rejected as invalid when reaching the server. So even though a client side route could be reached, the remote data for that route could not be.
