### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by nathasm** [auth0/auth0-angular2#6]
Looking at your SystemJS example. I cloned the project and did `npm install`.

When I ran the example I see in the console the following error:

    Uncaught ReferenceError: require is not defined.

Is that expected?

In trying to incorporate angular2-jwt in my own project, I am seeing the same error and being new to SystemJS, wasn't sure if it was me or systemic.

**Comment by chenkie** [comment]
That's coming from the Typescript module being `commonjs` instead of `system` so that the package can be used with Webpack. 

Since `angular2-jwt` is being mapped in the system config like this

```js
...

map: {
  "angular2-jwt": "node_modules/angular2-jwt/angular2-jwt"
}

...
```

we can actually take out the script tag that points to `angular2-jwt` in the `node_modules` folder.

Let me know if that works for you. I'm in the process of updating the examples which will reflect it.

Thanks

**Comment by nathasm** [comment]
I actually switched to using webpack instead so I can't confirm if this worked or not, closing for now.

**Comment by chenkie** [comment]
Cool :+1:

**Comment by larzKke** [comment]
I use Angular-CLI with Beta.11 and my SystemJS Config looks like this:
```
    System.config({
      packages: {
        app: {
            format: 'register',
            defaultExtension: 'js'
        },
        'angular2-jwt': {
            defaultExtension: 'js'
        }
      },
      map: {
        'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js'
      }
    });
    System.import('boot.js').then(null, console.error.bind(console));
```
but I get this error:
`http://localhost:4200/node_modules/angular2-jwt/angular2-jwt.js 404 (Not Found)`

**Comment by zakariamegza** [comment]
hello @chenkie  i need your help, i have a problem with angular2-jwt , i use angular2 RC4, with gulp and systemJs , i already done the mapping for angular2-jwt on systemJs.config and i did all what you recommended for others who had the same issue , but still have the famous error unexpected token in a file named with my Auth0ClientID.js (when i check its content i found chineese or somthing like that), when i change the module of tsconfig.json to commonJs i got an other error (Uncaught ReferenceError: require is not defined) and when i change it back to system i got unexpected token , i tried every thing i found in similar issues but always the same state , please help me if you can because i am blocked in that issue for 3 days and it drives me crazy
